import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { MdMarkEmailUnread } from "react-icons/md";

import { FaDiscord, FaInstagram } from "react-icons/fa";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" overflow-hidden px-10">
        <div className="main-content h-screen   flex  justify-between px-3 items-center">
          <div className=" max-w-xl ">
            <article className="pt-20">
              <h1 className="font-semibold text-6xl py-4">
                Membuat <span className="text-blue-500">Teknologi</span> Baru,
                Bersama Kami.
              </h1>
            </article>
            <form className="flex justify-start my-5 items-center gap-3">
              <label
                className="text-3xl hover:scale-110 hover:text-blue-500"
                htmlFor="email"
              >
                <MdMarkEmailUnread />
              </label>

              <input
                placeholder="Enter Your Email Here To Join..."
                id="email"
                className="duration-300 w-3/4 bg-transparent border-b-2 border-blue-500 outline-none  py-2  focus:py-3 focus:px-6 "
              />
            </form>

            <article className="pb-20">
              <p className="text-lg font-medium">
                Lorem Ipsum is simply dummy text of the printing and typesetting
                industry. Lorem Ipsum has been the industrys standard dummy text
                ever since the 1500s
              </p>
            </article>
            <ul className="flex  text-3xl justify-start gap-5 links items-center max-w-md  ">
              <li>
                <FaDiscord />
                <p className="text-lg">Join Discord</p>
              </li>
              <li>
                <FaInstagram />
                <p className="text-lg">Follow Instagram</p>
              </li>
            </ul>
          </div>
          <div>
            <Image
              height={200}
              width={600}
              src="/assets/images/heroes.png"
              alt="hero"
              priority
            />
          </div>
        </div>
      </main>
    </>
  );
}
